### ISSUE TITLE
numpy version

### ISSUE THREAD

**Issue by kuaileqipaoshui** [Open3DA/LL3DA#3]
Excuse me, when I tried bash scripts/opt-1.3b/train.generalist.sh, I meet a problem, that is "AttributeError: module 'numpy' has no attribute 'int'.     `np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information." So I try to reinstalled numpy=1.20, but there has a new problem: "ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject". 
What could I do? What's your numpy version? Did you have this problem? How was it resolved?
Looking forward to your reply.

**Comment by Hoyyyaard** [comment]
You just need to re-compile the utils/

**Comment by kuaileqipaoshui** [comment]
> You just need to re-compile the utils/

Thank you for your reply, this problem has been solved. But when I imported the opt-1.3b weights, there was another problem. What could I do?
![ll3da1](https://github.com/Open3DA/LL3DA/assets/137666741/8c75d3dd-ac6c-4098-b8ae-4d819f18df3c)

**Comment by ch3cook-fdu** [comment]
It seems like the weights of the LLM is not properly loaded. Please download the [pytorch_model.bin](https://huggingface.co/facebook/opt-1.3b/blob/main/pytorch_model.bin) file and put it under the local folder `./LL3DA/facebook/opt-1.3b`

**Comment by kuaileqipaoshui** [comment]
> It seems like the weights of the LLM is not properly loaded. Please download the [pytorch_model.bin](https://huggingface.co/facebook/opt-1.3b/blob/main/pytorch_model.bin) file and put it under the local folder `./LL3DA/facebook/opt-1.3b`

Thanks! I'm sorry to bother you again, there was another problem.
![ll3da2](https://github.com/Open3DA/LL3DA/assets/137666741/9778b02e-a9e6-4afe-997f-2719d5ac9148)

**Comment by kuaileqipaoshui** [comment]
> It seems like the weights of the LLM is not properly loaded. Please download the [pytorch_model.bin](https://huggingface.co/facebook/opt-1.3b/blob/main/pytorch_model.bin) file and put it under the local folder `./LL3DA/facebook/opt-1.3b`

Thanks! I'm sorry to bother you again, there was another problem.

File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/ll3da/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 240, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
File "/data/private/LL3DA/datasets/unified_densecap_scanrefer.py", line 118, in __getitem__
    match_mask = (ret_dict["gt_object_ids"] == target_obj_id).astype(np.float32)
TypeError: 'NoneType' object is not subscriptable

**Comment by ch3cook-fdu** [comment]
Please check whether you have prepared the ScanNet data correctly. Specifically, check the `ret_dict` output at [this](https://github.com/Open3DA/LL3DA/blob/main/datasets/unified_densecap_scanrefer.py#L102) line.

**Comment by WeitaiKang** [comment]
> You just need to re-compile the utils/

Hi, I still cannot fix it after re-compile. I deleted the whole `utils/` directory and copyed the original one from this codebase. And I used `python cython_compile.py build_ext --inplace` to re-compile. But I still have the save `module 'numpy' has no attribute 'int'.` problem.

Here's my re-compile output:

`
Compiling box_intersection.pyx because it changed.
[1/1] Cythonizing box_intersection.pyx
/home/kangweitai/anaconda3/envs/transvg/lib/python3.8/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/kangweitai/3DLLM/LL3DA/utils/box_intersection.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running build_ext
building 'box_intersection' extension
creating build
creating build/temp.linux-x86_64-cpython-38
gcc -pthread -B /home/kangweitai/anaconda3/envs/transvg/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/kangweitai/anaconda3/envs/transvg/lib/python3.8/site-packages/numpy/core/include/ -I/home/kangweitai/anaconda3/envs/transvg/include/python3.8 -c box_intersection.c -o build/temp.linux-x86_64-cpython-38/box_intersection.o
In file included from /home/kangweitai/anaconda3/envs/transvg/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1940:0,
                 from /home/kangweitai/anaconda3/envs/transvg/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/kangweitai/anaconda3/envs/transvg/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                 from box_intersection.c:1214:
/home/kangweitai/anaconda3/envs/transvg/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
creating build/lib.linux-x86_64-cpython-38
gcc -pthread -shared -B /home/kangweitai/anaconda3/envs/transvg/compiler_compat -L/home/kangweitai/anaconda3/envs/transvg/lib -Wl,-rpath=/home/kangweitai/anaconda3/envs/transvg/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-cpython-38/box_intersection.o -o build/lib.linux-x86_64-cpython-38/box_intersection.cpython-38-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-cpython-38/box_intersection.cpython-38-x86_64-linux-gnu.so -> 
`

**Comment by WeitaiKang** [comment]
I found changing numpy version, starting from 1.20 can solve this problem.
